repos:
  - repo: builtin
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-yaml

  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        entry: uv run ruff check
        language: system
        pass_filenames: false
        types_or: [python, pyi]
      - id: ruff-format
        name: ruff format
        entry: uv run ruff format
        language: system
        types_or: [python, pyi]
      - id: mypy
        name: mypy
        entry: uv run mypy
        language: system
        pass_filenames: false
        types_or: [python, pyi]
      - id: pytest
        name: pytest
        entry: uv run pytest
        language: system
        pass_filenames: false
        types_or: [python, pyi]
